### PR TITLE
io.js support

### PR DESCRIPTION
**Pull request by pwdtnx**
Added a support for io.js, which is a fork of node.js.

### CODE REVIEW

**Comment by devinus** [comment]
@riywo Any word on this?

**Comment by riywo** [comment]
Thanks @pwdtnx ! Currently I don't use this, so I added you to collaborators (also ndenv). Could you verify your PR and merge it by yourself?

**Comment by thedeeno** [comment]
@riywo what do you use?
@pwdtnx I'm interested in this pull request! :+1

**Comment by devinus** [comment]
@pwdtnx Does this PR assume OS X?

**Comment by pwdtnx** [comment]
@riywo Thanks!
@devinus This PR is developed and tested on OS X.

Sorry I took so long. Now this PR is merged.

**Pull request merged**
